apiVersion: podchaos.podchaosmonkey.pt/v1alpha1
kind: Monkey
metadata:
  name: monkey-sample
spec:
  noop: false
  interval: 1m
  namespace: workloads
  selector:
    matchLabels:
      chaosAllowed: "true"
